default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dsaf_development

test:
  <<: *default
  database: dsaf_test

production:
  <<: *default
  database: dsaf_production
  username: dsaf
  password: <%= ENV['DSAF_DATABASE_PASSWORD'] %>
